---
- name: AWS role
  ansible.builtin.import_role:
    name: aws
  vars:
    dns_record_list:
    - name: "{{ private_dns }}.{{ private_domain }}"
      zone: "{{ private_domain }}"
      type: A
      value: "{{ private_ip }}"
      private: true
      ttl: 120
    tags_facts:
      private_dns: "private_dns"
      private_domain: "private_domain"
      initial_master_nodes: "initial_master_nodes"
      data_snapshot: "data_snapshot"
      node_data: "node_data"
      node_master: "node_master"
      minimum_master_nodes: "minimum_master_nodes"
      es_cluster: "es_cluster"
      es_memory_size: "es_memory_size"
      seed_hosts: "seed_hosts"

- name: Elastic Role
  ansible.builtin.import_role:
    name: inqwise.stacktrek.elastic
  vars:
    es_user: "{{ app_user }}"
    es_group: "{{ app_group }}"
    es_data_dir: "{{ disk.mount }}/{{ disk.data_folder }}/data"
    es_log_dir: "{{ disk.mount }}/{{ disk.data_folder }}/log"
    es_config:
      network_host: "0.0.0.0"
      node_name: "{{ private_dns | default(ansible_hostname) }}"
      cluster_name: "{{ es_cluster_name }}"
      node_data: "{{ node_data }}"
      node_master: "{{ node_master }}"
    es_discovery:
      ec2:
        group: "elastic"
        host_type: "private_ip"
        auto_attributes: true
        awareness.attributes: "aws_availability_zone"
        es_cluster: "{{ es_cluster|default('') }}"
        initial_master_nodes: "{{ (initial_master_nodes|default('')).split(',')|select() }}"
        seed_hosts: "{{ (seed_hosts|default('')).split(',')|select() }}"
        minimum_master_nodes: "{{ minimum_master_nodes|default('') }}"
    memory_size: "{{ es_memory_size|default('') }}"
    ulimit:
      user: "{{ app_user }}"
