---
- name: restart elasticsearch
  become: yes
  service: name=elasticsearch state=restarted enabled=yes
  register: es_restarted

- name: reload systemd configuration
  become: yes
  systemd:
    daemon_reload: true
